### ISSUE TITLE
install.sh error message

### ISSUE THREAD

**Issue by guppie12** [michaelroland/sa-learn-cyrus#1]
The default CONF_PATH from install.sh was missing in my setup, however install.sh complained about a missing man path

Am i correct if I believe in install.sh,  line 100 should read:
    echo "${SCRIPT_NAME}: **$CONF_PATH** does not exist or is not a directory" >&2

rather than:
   echo "${SCRIPT_NAME}: $BASE_PATH/man does not exist or is not a directory" >&2

**Comment by michaelroland** [comment]
You are correct. Fixed in commit cb396e0.
